### ISSUE TITLE
'vue-cli-service' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by plumxxxxxxx** [EsunR/DormitoryManagement#24]
在clinet目录下输入npm run dev或者npm run build:prod的时候都会显示标题这个内容

**Comment by plumxxxxxxx** [comment]
npm install依赖装不上
![图片](https://github.com/EsunR/DormitoryManagement/assets/102129507/4832ca0e-a8e7-4615-afed-62e00267244e)

**Comment by EsunR** [comment]
1. 你没有安装 npm 包，vue-cli-server 指令找不到当然报错
2. npm 挂代理或者换国内源再试试

**Comment by plumxxxxxxx** [comment]
![图片](https://github.com/EsunR/DormitoryManagement/assets/102129507/928944ee-f28e-4a8e-99e2-a61e3869119e)
谢谢，上面的解决了，但是又来个新的

**Comment by plumxxxxxxx** [comment]
SSH连接超时问题解决了，在.ssh文件夹中创建config文本，按照图片内容，第二行是github账户邮箱
![图片](https://github.com/EsunR/DormitoryManagement/assets/102129507/d6cd6dcf-efd0-479a-8b0e-6b7c5d16b3d7)
