### ISSUE TITLE
大佬你好，我把项目clone到本地后，server端启动失败，求帮助！！！

### ISSUE THREAD

**Issue by mingyuesun** [EsunR/DormitoryManagement#26]
我在server目录下npm install 之后，执行 npm run db:init 和 npm run start 都会报错!求帮助！我想用这个项目做我的毕设😭
[QQ_1721879487884](https://github.com/user-attachments/assets/a7510922-7fc2-4cdc-843b-a3d01e9093c8)

**Comment by EsunR** [comment]
所以在issue里贴出报错信息啊。。。

**Comment by mingyuesun** [comment]
> 所以在issue里贴出报错信息啊。。。

来了来了，在执行 `npm run db:init` 之后就报这个歌错了，图片在下面👇

<img width="475" alt="image" src="https://github.com/user-attachments/assets/15f40cbd-5fa5-4979-9e24-586d39f41dd1">
<img width="486" alt="image" src="https://github.com/user-attachments/assets/b1175e44-cfaf-4b53-a2db-1a14dac9ab0d">

**Comment by EsunR** [comment]
> > 所以在issue里贴出报错信息啊。。。
> 
> 来了来了，在执行 `npm run db:init` 之后就报这个歌错了，图片在下面👇
> 
> <img alt="image" width="475" src="https://private-user-images.githubusercontent.com/31138694/356521228-15f40cbd-5fa5-4979-9e24-586d39f41dd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTMyMjgsIm5iZiI6MTcyMzE5MjkyOCwicGF0aCI6Ii8zMTEzODY5NC8zNTY1MjEyMjgtMTVmNDBjYmQtNWZhNS00OTc5LTllMjQtNTg2ZDM5ZjQxZGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4NDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0M2U1ZWU1MmEyZjI0NjE5NjJmOTBjMmNjYjg0NjM0ODliYWJmNTkwMmJjYzg5MmFhYzk5NzQzOTA2YWM2NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.elX9jt-oHs_cIkUCitrDJf34BBTAFev2yfjGPzUwvSA"> <img alt="image" width="486" src="https://private-user-images.githubusercontent.com/31138694/356521335-b1175e44-cfaf-4b53-a2db-1a14dac9ab0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTMyMjgsIm5iZiI6MTcyMzE5MjkyOCwicGF0aCI6Ii8zMTEzODY5NC8zNTY1MjEzMzUtYjExNzVlNDQtY2ZhZi00YjUzLWEyZGItMWExNGRhYzlhYjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4NDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMGUyZTM4ZWNkNDg5OTJmYWYzZmEzZGQyZDk5NmZkOTYzMTk5YzNkMzE4ZWNkOTUyMTE1NTFiZjg4OGJiYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.evrdCrAwiH5fvSn4kCdieI6di84kSAx_i7jThmmmWao">

看下 MySQL 版本

**Comment by mingyuesun** [comment]
> > > 所以在issue里贴出报错信息啊。。。
> > 
> > 
> > 来了来了，在执行 `npm run db:init` 之后就报这个歌错了，图片在下面👇
> > <img alt="image" width="475" src="https://private-user-images.githubusercontent.com/31138694/356521228-15f40cbd-5fa5-4979-9e24-586d39f41dd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTMyMjgsIm5iZiI6MTcyMzE5MjkyOCwicGF0aCI6Ii8zMTEzODY5NC8zNTY1MjEyMjgtMTVmNDBjYmQtNWZhNS00OTc5LTllMjQtNTg2ZDM5ZjQxZGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4NDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0M2U1ZWU1MmEyZjI0NjE5NjJmOTBjMmNjYjg0NjM0ODliYWJmNTkwMmJjYzg5MmFhYzk5NzQzOTA2YWM2NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.elX9jt-oHs_cIkUCitrDJf34BBTAFev2yfjGPzUwvSA"> <img alt="image" width="486" src="https://private-user-images.githubusercontent.com/31138694/356521335-b1175e44-cfaf-4b53-a2db-1a14dac9ab0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTMyMjgsIm5iZiI6MTcyMzE5MjkyOCwicGF0aCI6Ii8zMTEzODY5NC8zNTY1MjEzMzUtYjExNzVlNDQtY2ZhZi00YjUzLWEyZGItMWExNGRhYzlhYjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4NDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMGUyZTM4ZWNkNDg5OTJmYWYzZmEzZGQyZDk5NmZkOTYzMTk5YzNkMzE4ZWNkOTUyMTE1NTFiZjg4OGJiYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.evrdCrAwiH5fvSn4kCdieI6di84kSAx_i7jThmmmWao">
> 
> 看下 MySQL 版本

<img width="551" alt="image" src="https://github.com/user-attachments/assets/ffb14cbe-e7c4-475a-8a6e-33159cf349c6">

**Comment by EsunR** [comment]
换 mysql8 吧，我试了一下 mysql9 确实报错，版本太新了

**Comment by EsunR** [comment]
> 换 mysql8 吧，我试了一下 mysql9 确实报错，版本太新了

尝试修复了一下，最新的代码现在应该没问题了

https://github.com/EsunR/DormitoryManagement/commit/a15b3b8d56fd4f5b391acd870f3aa8f479c3f243#diff-d1d31d3fd7f11b0e94ebe03171af37a2a72108cde6c271f460a423d199cfcdeb

**Comment by mingyuesun** [comment]
> > 换 mysql8 吧，我试了一下 mysql9 确实报错，版本太新了
> 
> 尝试修复了一下，最新的代码现在应该没问题了
> 
> [a15b3b8#diff-d1d31d3fd7f11b0e94ebe03171af37a2a72108cde6c271f460a423d199cfcdeb](https://github.com/EsunR/DormitoryManagement/commit/a15b3b8d56fd4f5b391acd870f3aa8f479c3f243#diff-d1d31d3fd7f11b0e94ebe03171af37a2a72108cde6c271f460a423d199cfcdeb)

好滴，我试试，谢谢！
